server:
  port: 8888

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:mysql://localhost:3306/rest_fuzzer?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: