CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  canonical_name VARCHAR(255) NOT NULL,
  started_at TIMESTAMP,
  crashed_at TIMESTAMP,
  finished_at TIMESTAMP
) ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS suts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  location VARCHAR(255) NOT NULL,
  host VARCHAR(255) NOT NULL,
  basePath VARCHAR(255) NOT NULL
) ENGINE=INNODB;