const TASK_EXTRACTOR = "extractor";
const TASK_FUZZER = "fuzzer";

const TASK_STATUS_QUEUED = "QUEUED";
const TASK_STATUS_RUNNING = "RUNNING";
const TASK_STATUS_CRASHED = "CRASHED";
const TASK_STATUS_FINISHED = "FINISHED";

const REFRESH_TIMEOUT = 1000;

const PER_PAGE = 10;

const GET = "GET";
const POST = "POST";
const PUT = "PUT";
const PATCH = "PATCH";
const DELETE = "DELETE";
const HTTP_METHODS = [GET, POST, PUT, PATCH, DELETE];

const STATUS_NONE = "-";
const STATUS_OK = "2xx";
const STATUS_REDIRECTION = "3xx";
const STATUS_CLIENT_ERROR = "4xx";
const STATUS_SERVER_ERROR = "5xx";
const HTTP_RESPONSE_RANGES = [STATUS_NONE, STATUS_OK, STATUS_REDIRECTION, STATUS_CLIENT_ERROR, STATUS_SERVER_ERROR];

const AUTOMATIC = "AUTOMATIC";
const MANUAL = "MANUAL";
const DISCOVERY_MODES = [AUTOMATIC, MANUAL];

export default {
  TASK_EXTRACTOR: TASK_EXTRACTOR,
  TASK_FUZZER: TASK_FUZZER,

  TASK_STATUS_QUEUED: TASK_STATUS_QUEUED,
  TASK_STATUS_RUNNING: TASK_STATUS_RUNNING,
  TASK_STATUS_CRASHED: TASK_STATUS_CRASHED,
  TASK_STATUS_FINISHED: TASK_STATUS_FINISHED,

  REFRESH_TIMEOUT: REFRESH_TIMEOUT,

  PER_PAGE: PER_PAGE,

  HTTP_METHODS: HTTP_METHODS,

  GET: GET,
  POST: POST,
  PUT: PUT,
  PATCH: PATCH,
  DELETE: DELETE,
  HTTP_RESPONSE_RANGES:  HTTP_RESPONSE_RANGES,

  AUTOMATIC: AUTOMATIC,
  MANUAL: MANUAL,
  DISCOVERY_MODES: DISCOVERY_MODES
}