const TASK_EXTRACTOR = "extractor";
const TASK_GENERATOR = "generator";
const TASK_EXECUTOR = "executor";

const TASK_STATUS_QUEUED = "QUEUED";
const TASK_STATUS_RUNNING = "RUNNING";
const TASK_STATUS_CRASHED = "CRASHED";
const TASK_STATUS_FINISHED = "FINISEHD";

export default {
  TASK_EXTRACTOR: TASK_EXTRACTOR,
  TASK_GENERATOR: TASK_GENERATOR,
  TASK_EXECUTOR: TASK_EXECUTOR,

  TASK_STATUS_QUEUED: TASK_STATUS_QUEUED,
  TASK_STATUS_RUNNING: TASK_STATUS_RUNNING,
  TASK_STATUS_CRASHED: TASK_STATUS_CRASHED,
  TASK_STATUS_FINISHED: TASK_STATUS_FINISHED
}