const TASK_EXTRACTOR = "extractor";
const TASK_FUZZER = "fuzzer";

const TASK_STATUS_QUEUED = "QUEUED";
const TASK_STATUS_RUNNING = "RUNNING";
const TASK_STATUS_CRASHED = "CRASHED";
const TASK_STATUS_FINISHED = "FINISHED";

export default {
  TASK_EXTRACTOR: TASK_EXTRACTOR,
  TASK_FUZZER: TASK_FUZZER,

  TASK_STATUS_QUEUED: TASK_STATUS_QUEUED,
  TASK_STATUS_RUNNING: TASK_STATUS_RUNNING,
  TASK_STATUS_CRASHED: TASK_STATUS_CRASHED,
  TASK_STATUS_FINISHED: TASK_STATUS_FINISHED
}